=== Life-USTC/LU_js/declare-schema.json
{
    "title": "LU_js declare schema",
    "type": "object",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "version": {
            "type": "string"
        },
        "inputs": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "input_type"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "input_type": {
                        "type": "string",
                        "enum": [
                            "textfield",
                            "textarea",
                            "picker",
                            "enum_picker",
                            "checkbox"
                        ]
                    },
                    "is_password": {
                        "type": "boolean"
                    },
                    "default_value": {
                        "type": "string"
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "functions_supported": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "urls": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    }
}

=== Life-USTC/LU_js/ustc/declare.json
{
    "version": "1.0.0",
    "inputs": [
        {
            "name": "username",
            "input_type": "textfield"
        },
        {
            "name": "password",
            "input_type": "textfield",
            "is_password": true
        },
        {
            "name": "user_type",
            "input_type": "textfield",
            "options": [
                "graduate",
                "undergraduate"
            ]
        }
    ],
    "functions_supported": [
        "course_table",
        "score_list",
        "classroom_query"
    ],
    "urls": [
        "jw.ustc.edu.cn",
        "passport.ustc.edu.cn",
        "www.teach.ustc.edu.cn"
    ]
}
